# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wink', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WinkAPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=100)),
                ('client_password', models.CharField(max_length=100)),
            ],
        ),
    ]
